---
- name: simple playbook
  hosts: all
  gather_facts: false
  tasks:
  - name: first task
    debug:
      msg: first task
  - name: second task
    debug:
      msg: second task
  - name: third task
    debug:
      msg: third task
